remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

title: "The Trucker Codex Blog"
name: "The Trucker Codex"
description: "DOT & FMCSA Compliance Systems for Truckers"
url: "https://blog.thetruckercodex.com"
baseurl: ""
avatar: "/images/shoplogo.png"

permalink: /:title/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "single"
      author_profile: false
      read_time: true
      related: true
      sidebar:
        nav: "categories"
  - scope:
      path: "admin"
    values:
      sitemap: false

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - google05050009aaead19c.html
