backend:
  name: github
  repo: thetruckercodex/thetruckercodex.github.io
  branch: master
  base_url: https://sveltia-cms-auth.cdatelier52.workers.dev

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Categories"
        name: "categories"
        widget: "select"
        options:
          - "audits-violations"
          - "dqf"
          - "fmcsa-basics"
          - "hos-eld"
          - "maintenance"
          - "recordkeeping"
          - "roadside-inspection"
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Image Alt", name: "image_alt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
